# library(scde)
library(matrixStats)
library(plyr)
library(ppcor)
library(survival)
library(ROCR)
library(Hmisc)
library(rms)
library(mixtools)
library(lme4)
library(lmerTest)
attach(mtcars)
library(plotrix)
source(system.file("extdata", "ImmRes_output.R", package = "Mime1"))
source(system.file("extdata", "ImmRes_generic.R", package = "Mime1"))
source(system.file("extdata", "ImmRes_OE.R", package = "Mime1"))
source(system.file("extdata", "ImmRes_master.R", package = "Mime1"))
source(system.file("extdata", "ImmRes1_denovoCellTypeSig.R", package = "Mime1"))
source(system.file("extdata", "ImmRes2_immuneResistanceProgram.R", package = "Mime1"))
source(system.file("extdata", "ImmRes3_longitudinal.R", package = "Mime1"))
source(system.file("extdata", "ImmRes4_predictICBresponses.R", package = "Mime1"))
source(system.file("extdata", "ImmRes5_valCohort2.R", package = "Mime1"))
source(system.file("extdata", "ImmRes6_pancanDrug.R", package = "Mime1"))
