# library(scde)
library(matrixStats)
library(plyr)
library(ppcor)
library(survival)
library(ROCR)
library(Hmisc)
library(rms)
library(mixtools)
library(lme4)
library(lmerTest)
attach(mtcars)
library(plotrix)
source(system.file("R/IMPRES/ImmRes_output.R", package = "MIME"))
source(system.file("R/IMPRES/ImmRes_generic.R", package = "MIME"))
source(system.file("R/IMPRES/ImmRes_OE.R", package = "MIME"))
source(system.file("R/IMPRES/ImmRes_master.R", package = "MIME"))
source(system.file("R/IMPRES/ImmRes1_denovoCellTypeSig.R", package = "MIME"))
source(system.file("R/IMPRES/ImmRes2_immuneResistanceProgram.R", package = "MIME"))
source(system.file("R/IMPRES/ImmRes3_longitudinal.R", package = "MIME"))
source(system.file("R/IMPRES/ImmRes4_predictICBresponses.R", package = "MIME"))
source(system.file("R/IMPRES/ImmRes5_valCohort2.R", package = "MIME"))
source(system.file("R/IMPRES/ImmRes6_pancanDrug.R", package = "MIME"))
